export const BALL_MOVE = 'BALL_MOVE';
export const UPDATE_PADDLE_X = 'UPDATE_PADDLE_X';
export const CREATE_BRICK_GRID = 'CREATE_BRICK_GRID';
export const UPDATE_BRICK_GRID = 'UPDATE_BRICK_GRID';
export const UPDATE_BRICKS_LEFT = 'UPDATE_BRICKS_LEFT';
export const UPDATE_SCORE = 'UPDATE_SCORE';
export const UPDATE_LIVES = 'UPDATE_LIVES';
export const UPDATE_GAME_STATE = 'UPDATE_GAME_STATE';